contact_links:
  - name: Chat with the community
    url: https://discord.com/channels/618712310185197588/627204361545842688
    about: PSAppDeployToolkit channel on Discord (WinAdmins)
  - name: Join in the discussion
    url: https://discourse.psappdeploytoolkit.com
    about: PSAppDeployToolkit Discourse Forums
